version: "3"

networks:
  lecture21:
    external: false

volumes:
  # keycloak:
  #   driver: local
  mongo:
    driver: local

services:
  server1:
    image: server
    build: ./server
    environment:
      - MONGO_URL=mongodb://mongo
    depends_on:
      - mongo
    networks:
      - lecture21
  server2:
    image: server
    environment:
      - MONGO_URL=mongodb://mongo
    depends_on:
      - server1
    networks:
      - lecture21
  ui1:
    image: ui
    build: ./ui
    networks:
      - lecture21
  ui2:
    image: ui
    depends_on:
      - ui1
    networks:
      - lecture21
  load_balancer:
    image: nginx_load_balancer
    build: ./nginx-load-balancer
    networks:
      - lecture21
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - ui1
      - ui2
      - server1
      - server2
  # keycloak:
  #   image: keycloak
  #   container_name: keycloak
  #   environment:
  #     - KEYCLOAK_USER=keycloak
  #     # NOTE: this is only for demonstration purposes
  #     # ordinarily, you should NOT embed passwords in files
  #     - KEYCLOAK_PASSWORD=keycl0ak
  #   restart: always
  #   networks:
  #     - lecture21
  #   volumes:
  #     - keycloak:/opt/jboss/keycloak/standalone/data
  #   ports:
  #     - "127.0.0.1:8080:8080"
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    networks:
      - lecture21
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
